M48
; DRILL file KiCad 10.0.1 date 2026-10-03T00:28:47
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-03T00:28:47+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X104.99Y-107.61
X104.99Y-113.39
T2
X103.0Y-103.0
X103.0Y-118.0
T3
X232.0Y-103.0
X232.0Y-118.0
M30
